### ISSUE TITLE
SimpleCov and pushing

### ISSUE THREAD

**Issue by noshaf** [rurabe/drafthacker#1]
It looks like every time we use simplecov and then pull, we will get merge conflicts. I don't know if there is an easy way to get by it but I have been using git rm on the coverage file before every commit, because every time you run the tests it gets regenerated.

**Comment by sungchoi** [comment]
That's totally what I would normally do. I think though that after it is
regenerated by running guard, you can git ignore it. Ignoring it can only
be done before a file is added to the git index, but once it is done it
will never be added/tracked. I'll have try it out to be totally sure
though. Not sure how the fact that it was added at one point affects all
this.

Sung

**Comment by rurabe** [comment]
Yeah, i think gitignore is the way to go here
